type Params = {
  params: {
    userId: string;
  };
};
import GetUser from "@/lib/getUser";
import { Suspense } from "react";
import GetUserPost from "@/lib/getUserPost";
import UserPost from "./components/userPost";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "page",
  description: "Generated by create next app",
};

export default async function UserPage({ params: { userId } }: Params) {
  const userData: Promise<User> = await GetUser(userId);
  const userPostData: Promise<Posts[]> = await GetUserPost(userId);
  //   const [user, posts] = await Promise.all([userData, userPostData]);
  const user = await userData;
  return (
    <div>
      <p className=" text-red-700">{user.name}</p>
      <br />
      <Suspense fallback={<h2>loading....</h2>}>
        <UserPost promise={userPostData} />
      </Suspense>
    </div>
  );
}
