type Params = {
  params: {
    userId: string;
  };
};
import GetUser from "@/lib/getUser";
import { Suspense } from "react";
import GetUserPost from "@/lib/getUserPost";
import UserPost from "./components/userPost";
import { Metadata } from "next";
import GetAllUsers from "@/lib/getAllUsers";
import { notFound } from "next/navigation";
export const metadata: Metadata = {
  title: "user page",
  description: "Generated by create next app",
};

export default async function UserPage({ params: { userId } }: Params) {
  const userData: Promise<User> = await GetUser(userId);
  const userPostData: Promise<Posts[]> = await GetUserPost(userId);

  const user = await userData;

  if (!user.name) return notFound();

  return (
    <div>
      <p className=" text-red-700">{user.name}</p>
      <br />
      <Suspense fallback={<h2>loading....</h2>}>
        <UserPost promise={userPostData} />
      </Suspense>
    </div>
  );
}

export async function GenerateStaticParams() {
  const userData: Promise<User[]> = GetAllUsers();
  const users = await userData;

  return users.map((user) => ({
    userId: user.id.toString(),
  }));
}
